  export const alphapeticLettersData: { [key: string]: string[] } = {
    'A': ['about', 'abandon', 'asset', 'abduct','abolish','account','adorn','adopt','afflict'],
    'B': ['back', 'bag', 'bait', 'bar','bark','bathe','beach','betray','bill','blow'],
    'C': ['cab','calm','carol','certify','chart','chomp','cipher','circuit','click'],
    'D': ['dab','dam','dead','decay','defeat','delete','deploy','desire','detox','die'],
    'E': ['eat','earth','educate','egg','eject','embody','encode','engage','erupt','excess'],
    'F': ['flaw','fleck','flex','flesh','forge','format','fowl','free','frizz','freeze'],
    'G': ['gate','gain','gas','germinate','glass','goose','grill','gut','gulf','gulp'],
    'H': ['habit','hack','haft','hand','harm','harvest','hawk','heckle','high','honey'],
    'I': ['ice','idea','ill','impact','impart','improve','index','induce','infest','insect'],
    'J': ['jab','jack','jaw','jazz','jail','jiggle','jimmy','jingle','jinx','excess','jockey'],
    'K': ['keel','keen','keep','key','kidnap','king','kink','kiss','knee','knife','knot'],
    'L': ['label','lack','lace','lag','lamb','land','lord','last','lave','lay','law'],
    'M': ['machine','mad','magic','major','mail','mingle','make','malt','match','mark','menace'],
    'N': ['nab','nap','net','neuter','nose','notch','numb','nut','null','nurse','nuzzle'],
    'O': ['oar','obey','obscure','obsess','obstruct','occur','offload','offset','oil','oink','open'],
    'P': ['pace','pack','pain','pal','palm','palsy','pan','panic','paper','part','pass'],
    'Q': ['quack','quarry','qualify','quail','quarter','quash','quell','queue','quench','question','quill'],
    'R': ['rabbit','race','radiate','radio','raft','rage','rain','rate','ray','react','reciol'],
    'S': ['sell','sacrifice','saber','sail','sad','savage','scare','scope','swam','secure'],
    'T': ['tab','taper','taunt','teach','tear','team','taxi','tee','teeth','telecast'],
    'U': ['unbar','unbolt','under','unplug','unroll','untie','upset','utter'],
    'V': ['vacate','vacation','valet','value','valve','van','very'],
    'W': ['wage','water','wear','warm','war','wrong','while','wobble','worst'],
    'X': ['x-ray'],
    'Y': ['yarn','yawn','yatch','yell','yes','yo-yo','yield','yowl'],
    'Z': ['zag','zinc','zip','zone','zigzag','zonk','zoom','zero','zap','zest'],
  };